version: '3'
services:
  blockchain:
    build: .
    command: /go/bin/csd start

  goat:
    build: .
    command: ./scripts/startRESTserver.sh
    container_name: goat
    ports:
      - 1317:1317

  herd:
    image: nginx:latest
    container_name: herd
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
